### ISSUE TITLE
Reuse _accept_connection() of SelectorEventLoop

### ISSUE THREAD

**Issue by haypo** [saghul/aiouv#11]
Last week I modified SelectorEventLoop._accept_connection() to fix a bug (close the transport on error). I see that aiouv has copied an old copy (with the bug) of the function. Instead, aiouv should inherit from SelectorEventLoop, or we should retrieve the code differently.

At least, the bug should fix fixed: copy/paste the new code? :-(

**Comment by saghul** [comment]
We could indeed inherit from SelectorEventLoop. I remember considering it and going for the current approach, but I don't remember the reason :-(

**Comment by GMLudo** [comment]
+1 for inherit from SelectorEventLoop

**Comment by vstinner** [comment]
I'm not working on asyncio anymore, so I just close this issue.
