### ISSUE TITLE
can't install by pip on windows, linux

### ISSUE THREAD

**Issue by kernel0** [saghul/aiouv#15]
environment
-  OS : windows 10, windows server 2008 R2, Raspbian GNU/Linux 7 (wheezy)
-  python version : 3.4.3, 2.7.9
## printed below message.

``` shell
(python343) D:\venv\python343\Scripts>pip install aiouv
Collecting aiouv
  Could not find a version that satisfies the requirement aiouv (from versions:
)
No matching distribution found for aiouv
```

**Comment by saghul** [comment]
That's weird, it's up there on PyPI: https://pypi.python.org/pypi/aiouv

**Comment by kernel0** [comment]
@saghul I installed pyuv well by pip, but not aiouv. And so I compared two pip log.

``` shell
pip -vvv install pyuv
    Collecting pyuv
  Getting page https://pypi.python.org/simple/pyuv/
  1 location(s) to search for versions of pyuv:
  * https://pypi.python.org/simple/pyuv/
  Getting page https://pypi.python.org/simple/pyuv/
  Analyzing links from page https://pypi.python.org/simple/pyuv/
    Skipping link http://pypi.python.org/packages/cp27/p/pyuv/pyuv-1.0.0-cp27-none-win32.whl
     ....  the rest is omitted ...

pip -vvv install aiouv
  Getting page https://pypi.python.org/simple/aiouv/
  1 location(s) to search for versions of aiouv:
  * https://pypi.python.org/simple/aiouv/
  Getting page https://pypi.python.org/simple/aiouv/
  Analyzing links from page https://pypi.python.org/simple/aiouv/
  Could not find a version that satisfies the requirement aiouv (from versions: ) <---- (1) failed!!
```

And then checked difference of urls.
- https://pypi.python.org/simple/pyuv/
- https://pypi.python.org/simple/aiouv/

'https://pypi.python.org/simple/aiouv/' has no link!

**Comment by saghul** [comment]
I have no idea what changed in PyPI :-S You can install it straight from git for now.

**Comment by kernel0** [comment]
@saghul I also knew straight install. But straight install is not managed by 'requirements.txt' 

Install Issue is probably similar to  https://github.com/pypa/pip/issues/1649#issuecomment-37747134

Maybe you have to do `python setup.py sdist upload` for aiouv.

**Comment by kernel0** [comment]
I looked to find out more about extracting 'requirements.txt' of straight install (pip install github https url) . '-e' option helps this situation. Maybe this is a proper workaround of my issue. 

``` shell
pip install -e git+https://github.com/saghul/aiouv#egg=aiouv
```

and then 

``` shell
pip freeze > requirements.txt
```

requirements.txt shows

```
-e git+https://github.com/saghul/aiouv@76e21166055487aa699bc2ef31cb2639e92cbc92#egg=aiouv-master
```

@saghul  Can I close this issue?

**Comment by saghul** [comment]
Yeah, feel free to do so.
