### ISSUE TITLE
Inconsistent key names for extra kwarg in Transport classes

### ISSUE THREAD

**Issue by htoothrot** [saghul/aiouv#8]
aiouv's use of `'addr'` as the key name in the `extra` kwarg for the Transport classes is inconsistent. One place it refers to the result of getsockname() ([UDP transport](https://github.com/saghul/aiouv/blob/d37bea7579481b3baf3afd88e4f755846d6c2fe4/aiouv/_transports.py#L297)) and others to the result of getpeername() ([TCP transport](https://github.com/saghul/aiouv/blob/d37bea7579481b3baf3afd88e4f755846d6c2fe4/aiouv/_transports.py#L209)).

Additionally, asyncio itself uses `'sockname'` and `'peername'`. ([Example in library](https://github.com/python/cpython/blob/master/Lib/asyncio/selector_events.py#L513), [mention in docs](https://docs.python.org/3/library/asyncio-protocol.html#asyncio.BaseTransport.get_extra_info))

Suggesting key names are changed to match asyncio's usage.

Let me know your thoughts.

**Comment by saghul** [comment]
Agreed, care to send a PR?
